### ISSUE TITLE
Scanner significantly slowed down

### ISSUE THREAD

**Issue by OtoniArtur** [PokeMapMobile/PokeMapMobile#5]
So I just updated the PokeMapMobile to the latest version, and it seems that using the `-wh http://localhost:3001` flag that connects to the desktop application, the scanner is severely slowed down in comparison with it without `-wh...`. I'm using 6 accounts and it's almost as slow as using just one.

**Comment by PokeMapMobile** [comment]
Thanks for reporting the issue. I've looked into this and may have found the issue. The app doesn't return a response to the map. I'm guessing PokemonGo-Map will wait for a response for some time, and since a lot of requests go out, things can get slowed down. I'm uploading the fixed version right now, check for v0.0.2-a in a bit. See if that will fix it for you.

**Comment by OtoniArtur** [comment]
Doesn't seem to be fixed, i've noticed the workers are not scanning the area simultaneously, but instead the scans are taking ~10 secs(sometimes more) for each worker and then passing to the next one. For some reason the scanning is starting on step 7 (might be client). Thank you for the quick response though.

**Comment by PokeMapMobile** [comment]
Is this while the app is running? I am not able to reproduce it. It might be the case you are IP banned or another form of throttling by Niantic.

**Comment by OtoniArtur** [comment]
It might be a problem with the latest version of PokemonGo-Map, I've noticed the workers are not scanning simultaneously, but instead it's taking ~10 secs to scan and then passing to the next worker. Without the '-wh' the map runs normally, so not IP banned. Also for some reason the scan is starting at step 7.

**Comment by OtoniArtur** [comment]
Never mind, seems to be working fine now.
